### ISSUE TITLE
easier solution?

### ISSUE THREAD

**Issue by gherkins** [basecom/symfony-docker-edition#2]
I think changing the user id of the webserver/console-user
inside the container to you hosts user id would also solve the permission problem.
Without the need to modify any of symfony's code or setup permissions inside the container...

http://stackoverflow.com/questions/34949083/symfony-docker-permission-problems-for-cache-files

That works pretty good in our team with mixed OSs (ubuntu/win10/OSX).
Just my 2 cents though :)

**Comment by maxbeckers** [comment]
thanks @gherkins for this link. i'll test it that way :)
